customhost = "testdatabase.cfhe96st5iij.ap-south-1.rds.amazonaws.com"
customuser = "adminaws"
custompass = "adminaws123"
customdb = "testdatabase"
custombucket = "addnames"
customregion = "ap-south-1"
